name: docker-hub

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      imageName:
        description: '构建镜像的名称'
        required: true
      repoPath:
        description: 'git仓库路径'
        required: true
      dockerFileUrl:
        description: '自定义DockerFile下载路径,可空'
        required: false
      shellUrl:
        description: '自定义构建前脚本下载路径,可空'
        required: false
      platforms:
        description: '需要构建的平台'
        required: false
        default: linux/amd64,linux/arm64/v8
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      # 克隆目标,并且准备上下文
      - name: Git clone
        run: |
         rm -rf {*,.[^.]*,..?*}
         git clone "${{github.event.inputs.repoPath}}" .
         if [[ "${{ github.event.inputs.dockerFileUrl }}" ]] ;then wget "${{github.event.inputs.dockerFileUrl}}" -O ./Dockerfile ; fi
         if [[ "${{ github.event.inputs.shellUrl }}" ]] ;then wget "${{github.event.inputs.shellUrl}}" -O /tmp/.customize_shell.sh ; chmod +x /tmp/.customize_shell.sh && /tmp/.customize_shell.sh; fi

      # docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 设置 docker buildx 环境
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # build 前置操作
      - name: docker before
        id: docker_before
        run: |
          image="${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.inputs.imageName }}"
          echo "original image $image"
          arr=(${image//\// })
          image=""
          var_len=${#arr[*]}
          var_start=$(($var_len - 2))
          var_end=$(($var_len - 1))
          for ((i=$var_start; i<=$var_end ; i ++)); do image="${image}/${arr[$i]}"; done
          echo "format image name"
          echo "image=${image:1}" | tee -a $GITHUB_OUTPUT
          echo "tag=$(date +'%m-%d_%H-%M-%S')" | tee -a $GITHUB_OUTPUT
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes > /dev/null

      # build 并且 push docker 镜像
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{steps.docker_before.outputs.image}}:latest
            ${{steps.docker_before.outputs.image}}:${{steps.docker_before.outputs.tag}}
          platforms: ${{github.event.inputs.platforms}}
      
      # 打印 docker 镜像 SHA256 Hash 值
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
