name: '自定义构建并下载'

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      repoPath:
        description: 'git仓库路径'
        required: true
      SETTING_SEHLL_URL:
        description: '设置构建环境的shell地址'
        required: false
      BUILD_BEFORE_SHELL_URL:
        description: '构建前shell地址'
        required: false
      BUILD_SHELL_URL:
        description: '构建shell命令,输出要求输出文件'
        required: true
      BUILD_AFTER_SHELL_URL:
        description: '构建后shell命令'
        required: false
      BUILD_TARGET_PATH:
        description: '构建产物路径'
        required: true
      UPLOAD_TRANSFER:
        description: '上传服务,如wet,见github.com/Mikubill/transfer#support'
        required: false
      UPLOAD_RELEASE:
        description: '是否上传到RELEASE页面'
        required: false
        default: 'false'
      UPLOAD_TAG:
        description: '上传文件用的TAG,默认使用构建时间'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      # 产生tag
      - name: Generate tag
        id: tag
        run: |
          tag=build-customize_$(date +'%m-%d_%H-%M-%S')
          [ ! "${{github.event.inputs.UPLOAD_TAG}}" = "" ] && tag=${{github.event.inputs.UPLOAD_TAG}}
          echo "tag=$tag" >> $GITHUB_OUTPUT

      # 开始构建
      - name: Build
        id: build
        run: |
          rm -rf /tmp/dist
          mkdir -p /tmp/dist
          mkdir -p /tmp/build_log
          echo -e "github actions build\nstart time: $(date +'%Y-%m-%d %H:%M:%S')\n" > release.txt
          start=$(date +%s)
          //todo
          if [[ "${{ github.event.inputs.shellUrl }}" ]] ;then wget "${{github.event.inputs.shellUrl}}" -O /tmp/.customize_shell.sh ; chmod +x /tmp/.customize_shell.sh && /tmp/.customize_shell.sh; fi
          if [[ "${{ github.event.inputs.shellUrl }}" ]] ;then wget "${{github.event.inputs.shellUrl}}" -O /tmp/.customize_shell.sh ; chmod +x /tmp/.customize_shell.sh && /tmp/.customize_shell.sh; fi
          if [[ "${{ github.event.inputs.shellUrl }}" ]] ;then wget "${{github.event.inputs.shellUrl}}" -O /tmp/.customize_shell.sh ; chmod +x /tmp/.customize_shell.sh && /tmp/.customize_shell.sh; fi
          if [[ "${{ github.event.inputs.shellUrl }}" ]] ;then wget "${{github.event.inputs.shellUrl}}" -O /tmp/.customize_shell.sh ; chmod +x /tmp/.customize_shell.sh && /tmp/.customize_shell.sh; fi
          if [[ "${{ github.event.inputs.shellUrl }}" ]] ;then wget "${{github.event.inputs.shellUrl}}" -O /tmp/.customize_shell.sh ; chmod +x /tmp/.customize_shell.sh && /tmp/.customize_shell.sh; fi
          end=$(date +%s)
          take=$(( end - start ))
          echo "end time: $(date +'%Y-%m-%d %H:%M:%S')" >> release.txt
          echo "all build use ${take}s" >> release.txt
          echo >> release.txt
          cp -r /tmp/dist/ dist
          tar -zcvf dist.tar.gz dist > /dev/null

      # 上传构建日志
      - name: Upload build logs
        uses: actions/upload-artifact@main
        with:
          name: log_${{ steps.tag.outputs.tag }}
          path: /tmp/build_log
          retention-days: 1

      # 上传构建产物
      - name: Upload firmware directory
        uses: actions/upload-artifact@main
        with:
          name: ${{ steps.tag.outputs.tag }}
          path: dist.tar.gz
          retention-days: 1

      # 上传到中转服务
      - name: Upload firmware to transfer
        if: github.event.inputs.UPLOAD_TRANSFER && !failure() && !cancelled()
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./transfer ${{ github.event.inputs.UPLOAD_TRANSFER }} --no-progress dist.tar.gz 2>&1 | tee transfer.log
          url=$(cat transfer.log | grep https | cut -f3 -d" ")
          echo "🔗 External Download Link: $url" >> release.txt
          echo "::warning ::External Download Link: $url"

      # 生成release
      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        if: github.event.inputs.UPLOAD_RELEASE == 'true' && !failure() && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          body_path: release.txt
          files: dist/*
